namespace ImprovedSimpleLexer
{
    public enum TYPE
    {
        NONE, ID, INT, FLOAT, PLUS, MINUS, LBR, RBR, MUL, DIV, EOF, LSBR, RSBR,
        NAMESPACE, SEMICOLON, INT_TYPE, FLOAT_TYPE, FOR, DO, PRIVATE, PUBLIC, WHILE,
        LFBR, RFBR, ASSIGN, CLASS, STATIC, IF, ELSE, NEW, VOID, LESS, GREATER,
        LESS_EQUAL, GREATER_EQUAL, EQUAL, NOT_EQUAL, NOT, PLUS_SUM, MINUS_SUM,
        MUL_SUM, DIV_SUM, PLUS_PLUS, MINUS_MINUS, RETURN, AND, OR, VAR_TYPE, COLON,
        BOOL, BOOL_TYPE
    }

}
